Repository AjouCapstone-Sw/client, pull requests merged in 2022-11, with the labels that each got.

#14 Feat/product detail page
  package-lock.json
  package.json
  src/App.tsx
  src/Components/AuctionTimerButton/AuctionTimerButton.hook.ts
  src/Components/AuctionTimerButton/AuctionTimerButton.tsx
  src/Components/Button/Button.tsx
  src/Components/Calendar/Calendar.tsx
  src/Components/Footer/Footer.style.tsx
  src/Components/ImageSlick/ImageSlick.const.ts
  src/Components/ImageSlick/ImageSlick.style.ts
  src/Components/ImageSlick/ImageSlick.tsx
  src/Components/ItemListCell/ItemListCell.tsx
  src/Components/ItemListCell/ItemListCell.util.ts
  src/Components/Svg/LeftArrow.svg
  src/Components/Svg/RightArrow.svg
  src/Components/Svg/UserCircle.svg
  src/Components/Svg/index.ts
  src/Components/index.ts
  src/Pages/DetailPage/DetailPage.hook.ts
  src/Pages/DetailPage/DetailPage.style.tsx
  src/Pages/DetailPage/DetailPage.tsx
  src/Pages/DetailPage/DetailPage.type.ts
  src/Util/Product/index.ts
  src/Util/index.ts
Labels: enhancement, feat, discussion

#19 Feat/mainpage
  package-lock.json
  package.json
  public/asset/MainItemSet/더보기.svg
  public/asset/PlayButton.svg
  src/Components/Footer/Footer.tsx
  src/Components/Footer/Footer.util.tsx
  src/Components/HomeLiveItem/HomeLiveItem.style.ts
  src/Components/HomeLiveItem/HomeLiveItem.tsx
  src/Components/HomeLiveItem/HomeLiveItem.type.ts
  src/Components/MainItemSet/MainItem/MainItem.style.ts
  src/Components/MainItemSet/MainItem/MainItem.tsx
  src/Components/MainItemSet/MainItem/MainItem.type.ts
  src/Components/MainItemSet/MainItemSet.const.ts
  src/Components/MainItemSet/MainItemSet.hook.tsx
  src/Components/MainItemSet/MainItemSet.style.ts
  src/Components/MainItemSet/MainItemSet.tsx
  src/Components/MainItemSet/MainItemSet.type.ts
  src/Components/MainItemSet/MainItemset.util.ts
  src/Components/ProductHeader/ProductHeader.style.tsx
  src/Components/index.ts
  src/Pages/FooterPage/FooterPage.style.ts
  src/Pages/FooterPage/FooterPage.tsx
  src/Pages/HomePage/HomePage.hook.tsx
  src/Pages/HomePage/HomePage.style.ts
  src/Pages/HomePage/HomePage.tsx
  src/Pages/HomePage/HomePage.util.ts
  src/Pages/ProductPage/ProductPage.style.ts
  src/Pages/ProductPage/ProductPage.tsx
  src/_msw/Category/handler.ts
  src/_msw/Category/index.ts
  src/_msw/index.ts
  src/_msw/index.tsx
  src/_msw/type.ts
Labels: feat

#20 Feat/theme provider
  src/Components/Button/Button.tsx
  src/Components/Footer/Footer.style.tsx
  src/Components/HomeLiveItem/HomeLiveItem.style.ts
  src/Components/ImageSlick/ImageSlick.style.ts
  src/Components/ItemListCell/ItemListCell.style.tsx
  src/Components/MainItemSet/MainItem/MainItem.style.ts
  src/Components/MainItemSet/MainItemSet.style.ts
  src/Components/ProductHeader/ProductHeader.style.tsx
  src/Pages/DetailPage/DetailPage.style.tsx
  src/Pages/LoginPage/LoginPage.style.ts
  src/Pages/RegisterPage/RegisterPage.style.ts
  src/Styles/theme.ts
  src/Styles/theme.type.ts
  src/Types/styled.ts
  src/Types/svg.d.ts
  src/main.tsx
Labels: feat

#25 Feat/product reigister page
  src/App.tsx
  src/Components/AuctionEditForm/AuctionEditForm.const.ts
  src/Components/AuctionEditForm/AuctionEditForm.tsx
  src/Components/AuctionEditForm/AuctionEditForm.type.ts
  src/Components/DateTimePicker/DateTimePicker.tsx
  src/Components/DateTimePicker/DateTimePicker.type.ts
  src/Components/Header/Header.const.ts
  src/Components/Header/Header.tsx
  src/Components/ImageSlick/ImageSlick.style.ts
  src/Components/ImageSlider/ImageSlider.style.ts
  src/Components/ImageSlider/ImageSlider.tsx
  src/Components/ImageSlider/ImageSlider.type.ts
  src/Components/RangeSlider/RangeSlider.tsx
  src/Components/RangeSlider/RangeSlider.type.ts
  src/Components/Svg/AddImage.svg
  src/Components/Svg/index.ts
  src/Components/index.ts
  src/Pages/HeaderPage/HeaderPage.style.ts
  src/Pages/HeaderPage/HeaderPage.tsx
  src/Pages/HeaderPage/index.ts
  src/Pages/ProductPage/ProductPage.tsx
  src/Pages/ProductPage/index.ts
  src/Pages/ProductRegisterPage/ProductRegisterPage.const.ts
  src/Pages/ProductRegisterPage/ProductRegisterPage.hook.ts
  src/Pages/ProductRegisterPage/ProductRegisterPage.style.ts
  src/Pages/ProductRegisterPage/ProductRegisterPage.tsx
  src/Pages/ProductRegisterPage/ProductRegisterPage.type.ts
  src/Pages/ProductRegisterPage/ProductRegisterPage.util.ts
  src/Pages/ProductRegisterPage/index.ts
  src/Pages/index.ts
  src/Styles/theme.ts
  src/Util/Product/index.ts
Labels: enhancement, feat

#27 Enhance/product register page
  src/Components/AuctionEditForm/AuctionEditForm.tsx
  src/Components/DateTimePicker/DateTimePicker.type.ts
  src/Components/FormErrorMessage/FormErrorMessage.style.ts
  src/Components/FormErrorMessage/FormErrorMessage.tsx
  src/Components/index.ts
  src/Pages/ProductRegisterPage/ProductRegisterPage.style.ts
  src/Pages/ProductRegisterPage/ProductRegisterPage.tsx
  src/Pages/RegisterPage/RegisterPage.style.ts
  src/Pages/RegisterPage/RegisterPage.tsx
Labels: enhancement

#26 Feat/mypage
  .eslintrc.json
  public/asset/Star/empty.svg
  public/asset/Star/fill.svg
  src/Components/AuctionReview/AuctionReview.style.ts
  src/Components/AuctionReview/AuctionReview.tsx
  src/Components/AuctionReview/index.ts
  src/Components/ItemListCell/ItemListCell.style.tsx
  src/Components/ItemListCell/ItemListCell.tsx
  src/Components/MyPageUser/MyPageUser.tsx
  src/Components/MyPageUser/MyPageUser.type.ts
  src/Components/MyPageUser/index.ts
  src/Components/ProductReview/ProductReview.style.ts
  src/Components/ProductReview/ProductReview.tsx
  src/Components/ProductReview/index.ts
  src/Components/index.ts
  src/Pages/DetailPage/DetailPage.const.ts
  src/Pages/DetailPage/DetailPage.hook.ts
  src/Pages/FooterPage/FooterPage.style.ts
  src/Pages/ListPage/ListPage.hook.tsx
  src/Pages/ListPage/ListPage.tsx
  src/Pages/ListPage/ListPage.type.ts
  src/Pages/MyPage/MyPage.const.ts
  src/Pages/MyPage/MyPage.hook.tsx
  src/Pages/MyPage/MyPage.style.ts
  src/Pages/MyPage/MyPage.tsx
  src/Pages/MyPage/MyPage.type.ts
  src/Pages/MyPage/MyPage.util.ts
  src/Pages/MyPage/MyPageBody/MyPageBody.tsx
  src/Pages/MyPage/MyPageBody/MyPageBody.util.ts
  src/Styles/theme.ts
  src/Util/Star/index.tsx
  src/_msw/Review/const.ts
  src/_msw/Review/handler.ts
  src/_msw/Review/index.ts
  src/_msw/User/const.ts
  src/_msw/User/handler.ts
  src/_msw/User/index.ts
  src/_msw/index.ts
Labels: feat

#24 Feat/web rtc
  .eslintrc.json
  package-lock.json
  public/asset/Auction/Exit.svg
  public/asset/Auction/Like.svg
  public/asset/Auction/PeopleCount.svg
  public/asset/Auction/Sound.svg
  src/App.tsx
  src/Components/Buyer/Buyer.hook.tsx
  src/Components/Buyer/Buyer.tsx
  src/Components/Buyer/Buyer.type.ts
  src/Components/Buyer/Buyer.util.ts
  src/Components/Buyer/index.ts
  src/Components/MainItemSet/MainItemset.util.ts
  src/Components/Seller/Seller.hook.tsx
  src/Components/Seller/Seller.tsx
  src/Components/Seller/Seller.type.ts
  src/Components/Seller/Seller.util.ts
  src/Components/Seller/index.ts
  src/Components/Video/Video.style.ts
  src/Components/Video/Video.tsx
  src/Components/Video/index.ts
  src/Components/WebRTCView/WebRTCView.const.ts
  src/Components/WebRTCView/WebRTCView.hook.tsx
  src/Components/WebRTCView/WebRTCView.style.ts
  src/Components/WebRTCView/WebRTCView.tsx
  src/Components/WebRTCView/WebRTCView.type.ts
  src/Components/WebRTCView/WebRTCView.util.ts
  src/Components/WebRTCView/WebRTCViewBody/WebRTCViewBody.tsx
  src/Components/WebRTCView/WebRTCViewBody/WebRTCViewBody.type.ts
  src/Components/WebRTCView/WebRTCViewBody/index.ts
  src/Components/WebRTCView/WebRTCViewFooter/WebRTCViewFooter.hook.tsx
  src/Components/WebRTCView/WebRTCViewFooter/WebRTCViewFooter.style.ts
  src/Components/WebRTCView/WebRTCViewFooter/WebRTCViewFooter.tsx
  src/Components/WebRTCView/WebRTCViewFooter/WebRTCViewFooter.type.ts
  src/Components/WebRTCView/WebRTCViewFooter/WebRTCViewFooter.util.ts
  src/Components/WebRTCView/WebRTCViewHeader/WebRTCViewHeader.style.ts
  src/Components/WebRTCView/WebRTCViewHeader/WebRTCViewHeader.tsx
  src/Components/WebRTCView/WebRTCViewHeader/index.ts
  src/Components/WebRTCView/index.ts
  src/Components/index.ts
  src/Pages/LivePage/LivePage.tsx
  src/Socket/WebRTC/WebRTC.const.ts
  src/Socket/WebRTC/WebRTC.ts
  src/Socket/WebRTC/WebRTC.type.tsx
  src/Socket/WebRTC/WebRTC.util.ts
  src/Socket/WebRTC/index.ts
  src/_msw/Auction/handler.ts
  src/_msw/Auction/index.ts
  src/_msw/index.ts
  tsconfig.json
  vite.config.ts
Labels: feat

#29 Fix/detail page
  src/Components/AuctionTimerButton/AuctionTimerButton.hook.ts
  src/Components/AuctionTimerButton/AuctionTimerButton.tsx
  src/Pages/DetailPage/DetailPage.style.tsx
  src/Pages/DetailPage/DetailPage.tsx
Labels: feat

#28 Feat/product edit page
  src/App.tsx
  src/Components/AuctionEditForm/AuctionEditForm.type.ts
  src/Components/Buyer/Buyer.util.ts
  src/Components/ProductRegisterForm/ProductRegisterForm.const.ts
  src/Components/ProductRegisterForm/ProductRegisterForm.hook.ts
  src/Components/ProductRegisterForm/ProductRegisterForm.style.ts
  src/Components/ProductRegisterForm/ProductRegisterForm.tsx
  src/Components/ProductRegisterForm/ProductRegisterForm.type.ts
  src/Components/ProductRegisterForm/ProductRegisterForm.util.ts
  src/Components/Video/Video.tsx
  src/Components/WebRTCView/WebRTCViewFooter/WebRTCViewFooter.tsx
  src/Components/index.ts
  src/Pages/DetailPage/DetailPage.const.ts
  src/Pages/DetailPage/DetailPage.style.tsx
  src/Pages/DetailPage/DetailPage.tsx
  src/Pages/DetailPage/DetailPage.type.ts
  src/Pages/DetailPage/DetailPage.util.ts
  src/Pages/DetailPage/index.ts
  src/Pages/ProductEditPage/ProductEditPage.hook.ts
  src/Pages/ProductEditPage/ProductEditPage.tsx
  src/Pages/ProductEditPage/ProductEditPage.util.ts
  src/Pages/ProductEditPage/index.ts
  src/Pages/ProductRegisterPage/ProductRegisterPage.const.ts
  src/Pages/ProductRegisterPage/ProductRegisterPage.tsx
  src/Pages/index.ts
  src/Util/Product/index.ts
  src/_msw/ProductDetail/const.ts
Labels: feat
