Repository AjouCapstone-Sw/client, pull requests merged in 2022-10, with the labels that each got.

#2 enhance: prevent Branch close [#1]
  .husky/pre-push
Labels: enhancement

#3 Feat/login page
  .eslintrc.json
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/App.css
  src/App.tsx
  src/Components/Button/Button.tsx
  src/Components/Input/Input.tsx
  src/Components/index.ts
  src/Hook/index.ts
  src/Hook/useMovePage.tsx
  src/Hook/useToggle.tsx
  src/Pages/DetailPage/DetailPage.tsx
  src/Pages/DetailPage/index.ts
  src/Pages/HomePage/HomePage.tsx
  src/Pages/HomePage/index.ts
  src/Pages/ListPage/ListPage.tsx
  src/Pages/ListPage/index.ts
  src/Pages/LivePage/LivePage.tsx
  src/Pages/LivePage/index.ts
  src/Pages/LoginPage/LoginPage.hook.tsx
  src/Pages/LoginPage/LoginPage.style.ts
  src/Pages/LoginPage/LoginPage.tsx
  src/Pages/LoginPage/index.ts
  src/Pages/MyPage/MyPage.tsx
  src/Pages/MyPage/index.ts
  src/Pages/RegisterPage/RegisterPage.tsx
  src/Pages/RegisterPage/index.ts
  src/Pages/index.ts
  src/Util/index.ts
  src/main.tsx
  tsconfig.json
  vite.config.ts
Labels: feat

#7 Feat/init socket
  package-lock.json
  package.json
  src/Socket/Chat/index.ts
  src/Socket/Chat/joinChatRoom.ts
  src/Socket/Chat/leaveChatRoom.ts
  src/Socket/Chat/sendMessage.ts
  src/Socket/emitEvent.ts
  src/Socket/index.ts
  src/Socket/initSocket.ts
  src/Socket/registerSocketEvent.ts
  src/Socket/socket.ts
Labels: feat

#9 Feat/register page
  package-lock.json
  package.json
  src/Components/Button/Button.tsx
  src/Components/Calendar/Calendar.tsx
  src/Components/Calendar/Calendar.type.ts
  src/Components/Dropdown/Dropdown.style.ts
  src/Components/Dropdown/Dropdown.tsx
  src/Components/Dropdown/Dropdown.type.ts
  src/Components/index.ts
  src/Pages/RegisterPage/RegisterPage.const.ts
  src/Pages/RegisterPage/RegisterPage.hook.ts
  src/Pages/RegisterPage/RegisterPage.style.ts
  src/Pages/RegisterPage/RegisterPage.tsx
Labels: feat

#12 Feat/listpage
  .eslintrc.json
  package-lock.json
  package.json
  public/asset/김영진.jpg
  src/App.css
  src/App.tsx
  src/Components/Footer/Footer.const.tsx
  src/Components/Footer/Footer.style.tsx
  src/Components/Footer/Footer.tsx
  src/Components/Footer/Footer.util.tsx
  src/Components/ItemListCell/ItemListCell.style.tsx
  src/Components/ItemListCell/ItemListCell.tsx
  src/Components/ItemListCell/ItemListCell.type.ts
  src/Components/ItemListCell/ItemListCell.util.ts
  src/Components/ProductHeader/ProductHeader.style.tsx
  src/Components/ProductHeader/ProductHeader.tsx
  src/Components/Svg/Cart.svg
  src/Components/Svg/Home.svg
  src/Components/Svg/Person.svg
  src/Components/Svg/Search.svg
  src/Components/Svg/Video.svg
  src/Components/Svg/index.ts
  src/Components/index.ts
  src/Hook/useMovePage.tsx
  src/Pages/FooterPage/FooterPage.tsx
  src/Pages/FooterPage/index.ts
  src/Pages/ListPage/ListPage.hook.tsx
  src/Pages/ListPage/ListPage.tsx
  src/Pages/ListPage/ListPage.type.ts
  src/Pages/LoginPage/LoginPage.tsx
  src/Pages/MyPage/MyPage.tsx
  src/Pages/ProductPage/ProductPage.tsx
  src/Pages/ProductPage/index.ts
  src/Pages/index.ts
  src/custom.d.ts
  tsconfig.json
  vite.config.ts
Labels: feat, discussion
